2025-06-11 00:55:03,120 - INFO - Starting sector portfolios generation for 2025-06-10
2025-06-11 00:55:14,399 - ERROR - Error during sector portfolios generation
Traceback (most recent call last):
  File "C:\Users\kvs39\Desktop\validityBase\Dagster\portfolio_spdrs\dagster_pipelines\assets\portfolio_asset.py", line 58, in sector_portfolios
    df_portfolios: pd.DataFrame = produce_sector_portfolios(partition_date, logger=file_logger, half_life=30)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kvs39\Desktop\validityBase\Dagster\portfolio_spdrs\dagster_pipelines\assets\portfolio_producer.py", line 152, in produce_sector_portfolios
    if np.isnan(beta):
       ^^^^^^^^^^^^^^
  File "C:\Users\kvs39\Desktop\validityBase\Dagster\dagster_env\Lib\site-packages\pandas\core\generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
